extension_dir = "C:\laragon\bin\php\php-8.3.30-Win32-vs16-x64\ext"
extension=openssl
extension=curl
extension=mbstring
extension=fileinfo
extension=pdo_mysql
extension=pdo_sqlite
extension=sqlite3
extension=gd
extension=zip
